{% set name = "geotiff" %}
{% set version = "1.4.2" %}
{% set sha256 = "ad87048adb91167b07f34974a8e53e4ec356494c29f1748de95252e8f81a5e6e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://download.osgeo.org/geotiff/lib{{ name }}/lib{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    # - {{ compiler('c') }}
    # - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - proj4
    - zlib
    - jpeg
    - libtiff
    - libgdal {{ libgdal }}
    - proj4
    - libspatialite

test:
  commands:
    - test -f $PREFIX/lib/libgeotiff.so                 # [linux]
    - if not exist %LIBRARY_LIB%\\geotiff_i.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\geotiff.dll exit 1    # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]

about:
  home: https://trac.osgeo.org/geotiff
  license: MIT
  license_file: LICENSE
  summary: 'TIFF based interchange format for georeferenced raster imagery'

  # The remaining entries in this section are optional, but recommended
  description: |
    GeoTIFF represents an effort by over 160 different remote sensing,
    GIS, cartographic, and surveying related companies and organizations
    to establish a TIFF based interchange format for georeferenced raster imagery.

extra:
  recipe-maintainers:
    - v-turin
